"""allow wallet ids to be None in transaction model

Revision ID: 9510d771cef7
Revises: 6d64ba5df4dd
Create Date: 2026-05-25 14:27:49.358771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9510d771cef7'
down_revision: Union[str, Sequence[str], None] = '6d64ba5df4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('from_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('to_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('to_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('from_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
